import { RainbowKitProvider, Theme } from "@rainbow-me/rainbowkit";

export const myCustomTheme: Theme = {
  blurs: {
    modalOverlay: "blur(40px)",
  },
  colors: {
    accentColor: "#8FB1FF",
    actionButtonBorder: "#374151",
    accentColorForeground: "white",
    actionButtonBorderMobile: "#8FB1FF",
    modalBackground: "#222A39",
    modalBorder: "#334155",
    modalText: "white",
    connectButtonText: "white",
    menuItemBackground: "#222A39",
    modalTextDim: "white",
    modalTextSecondary: "#A3B1C6",
    connectButtonBackground: "#334155",
    closeButton: "white",
    actionButtonSecondaryBackground: "...",
    closeButtonBackground: "...",
    connectButtonBackgroundError: "...",
    connectButtonInnerBackground: "...",
    connectButtonTextError: "...",
    connectionIndicator: "...",
    error: "...",
    generalBorder: "...",
    generalBorderDim: "...",
    modalBackdrop: "...",
    profileAction: "...",
    profileActionHover: "...",
    profileForeground: "...",
    selectedOptionBorder: "...",
    standby: "...",
  },
  fonts: {
    body: "...",
  },
  radii: {
    modal: "20px",
    menuButton: "13px",
    actionButton: "15px",
    connectButton: "...",
    modalMobile: "...",
  },
  shadows: {
    connectButton: "...",
    dialog: "...",
    profileDetailsAction: "...",
    selectedOption: "...",
    selectedWallet: "...",
    walletLogo: "...",
  },
};
